### ISSUE TITLE
Email deliverability fails to protonmail.com

### ISSUE THREAD

**Issue by GNU-Plus-Windows-User** [Snawoot/postfix-mta-sts-resolver#99]
**Describe the bug**
I've installed postfix-mta-sts-resolver on my iRedMail email server but email deliverability fails when I send an email to ProtonMail, however I can send emails with a verified TLS connection to Gmail and Outlook.
I tried to install via pip and snap but both versions don't work, ``/etc/mta-sts-daemon.yml`` is missing, no systemd service is created and nothing is listening on port 8461 in both cases so I'm not sure if this is an issue with my installation method or an actual bug.

**To Reproduce**
1. Install via apt ``sudo apt install postfix-mta-sts-resolver`` on Ubuntu 22.04 with iRedMail
2. Add ``smtp_tls_policy_maps = socketmap:inet:127.0.0.1:8461:postfix`` into postfix ``main.cf``
3. Use postfix-mta-sts-resolver config provided below
4. Send an email to protonmail

**postfix-mta-sts-resolver config**
```
host: 127.0.0.1
port: 8461
reuse_port: true
shutdown_timeout: 20
cache:
  type: internal
  options:
    cache_size: 10000
default_zone:
  strict_testing: false
  timeout: 20
proactive_policy_fetching:
  enabled: true
```

**Expected behavior**
I should be able to send emails to protonmail no problem, according to hardenize mta-sts is setup correctly for protonmail.com.

**Output listings**

**Logs**
```
May 26 22:06:22 mail postfix/smtp[80090]: CA certificate verification failed for mail.protonmail.ch[176.119.200.128]:25: num=2:unable to get issuer certificate
May 26 22:06:22 mail postfix/smtp[80090]: Untrusted TLS connection established to mail.protonmail.ch[176.119.200.128]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
May 26 22:06:22 mail postfix/smtp[80090]: 4QSNgT0FWpz9wJP: Server certificate not verified
```

**mta-sts-query domain protonmail.com**
```
(<STSFetchResult.NONE: 0>, None)
```

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Python version: [Unknown]
